#!/bin/bash
# MANUAL TEST GUIDE - Critical Flow Validation
# Run these tests in the browser at http://localhost:5001

echo "=========================================="
echo "CRITICAL FLOW VALIDATION TESTS"
echo "=========================================="
echo ""
echo "App URL: http://localhost:5001"
echo ""
echo "TEST SEQUENCE:"
echo "1. Load app and ensure no crashes"
echo "2. Add Customer without photos"
echo "3. Verify customer appears after refresh"
echo "4. Add Customer with photos"
echo "5. Verify customer with photos appears after refresh"
echo "6. Add Vehicle via dropdown"
echo "7. Verify vehicle options are not duplicated"
echo "8. Add Vehicle with 'Other' brand"
echo "9. Verify vehicle appears after refresh"
echo ""
echo "EXPECTED OUTCOMES:"
echo "✓ App loads without TypeError or ReferenceError"
echo "✓ Customer form shows all fields"
echo "✓ Photo upload doesn't freeze"
echo "✓ Vehicle type dropdown shows: Bike, Car, Scooter, EV (no duplicates)"
echo "✓ Brand dropdown populates based on selected type"
echo "✓ Model dropdown populates based on brand"
echo "✓ No 'Other' appears multiple times"
echo "✓ Customer persists after page refresh"
echo "✓ Vehicle persists after page refresh"
echo ""
